---
kind: pipeline
name: deploy
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      dry_run: true
      repo: drone-elastic-beanstalk
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: ghcr.io/goodwillaz/drone-elastic-beanstalk
      registry: ghcr.io
      username: goodwillaz-ci
      password:
        from_secret: gh_token
    when:
      event:
        exclude:
          - pull_request

trigger:
  ref:
    - refs/heads/develop
    - "refs/tags/**"
    - "refs/pull/**"
